export const DEMOGRAPHIC_QUESTION_CHOICES = {
  gender: {
    label: 'Gender',
    choices: ['male', 'female'],
    showOthers: false,
  },
  ethnicity: {
    label: 'Ethnicity',
    choices: ['Chinese', 'Malay', 'Indian', 'White European'],
    showOthers: true,
  },
  residentialStatus: {
    label: 'Residential Status',
    choices: [
      'Singapore citizen',
      'Permanent resident',
      'Student pass',
      'Employment pass',
      'Work Permit / S pass',
    ],
    showOthers: true,
  },
  district: {
    label: 'Home Address',
    choices: [
      'Raffles Place, Marina, Cecil',
      'Tanjong Pagar, Chinatown',
      'Tiong Bahru, Alexandra, Queenstown',
      'Mount Faber, Telok Blangah, Harbourfront',
      'Buona Vista, Pasir Panjang, Clementi',
      'Clarke Quay, City Hall,',
      'Bugis, Beach Road, Golden Mile',
      'Little India, Farrer Park',
      'Orchard Road, River Valley',
      'Bukit Timah, Holland, Balmoral',
      'Novena, Newton, Thomson',
      'Toa Payoh, Serangoon, Balestier',
      'Macpherson, Braddell,',
      'Geylang, Paya Lebar, Sims',
      'Joo Chiat, Marina Parade, Katong',
      'Bedok, Upper East Coast, Siglap',
      'Changi, Flora, Loyang',
      'Tampines, Pasir Ris',
      'Punggol, Sengkang, Serangoon Gardens',
      'Ang Mo Kio, Bishan, Thomson',
      'Upper Bukit Timah, Ulu Pandan, Clementi Park',
      'Boon Lay, Jurong, Tuas',
      'Choa Chu Kang, Diary Farm, Hillview, Bukit',
      'Panjang, Bukit Batok',
      'Kranji, Lim Chu Kang, Tengah',
      'Woodlands, Admiralty',
      'Upper Thomson, Mandai',
      'Sembawang, Yishun, Admiralty',
      'Yio Chu Kang, Seletar',
      'Not Applicable',
    ],
    showOthers: false,
  },
  addressDuringSem: {
    label: 'Semester Address',
    choices: [
      'Same as home address',
      'On campus residence',
      'Off campus residence different from home address',
      "Don't know yet",
    ],
    showOthers: false,
  },
  school: {
    label: 'School',
    choices: [],
    showOthers: true,
  },
  onCampusAddress: {
    label: 'Campus Address',
    choices: [
      'Unsure',
      'Hall 1',
      'Hall 2',
      'Hall 3',
      'Hall 4',
      'Hall 5',
      'Hall 6',
      'Hall 7',
      'Hall 8',
      'Hall 9',
      'Hall 10',
      'Hall 11',
      'Hall 12',
      'Hall 13',
      'Hall 14',
      'Hall 15',
      'Hall 16',
      'Crescent Hall',
      'Pioneer Hall',
      'Binjai Hall',
      'Tanjong Hall',
      'Banyan Hall',
      'Saraca Hall',
      'Tamarind Hall',
      'Meranti Hall',
      'Graduate Hall 1',
      'Graduate Hall 2',
    ],
    showOthers: true,
  },
  offCampusAddress: {
    label: 'Off campus address',
    choices: [],
    showOthers: true,
  },
  facultyOfStudy: {
    label: 'Faculty of Study',
    choices: [
      'Asian School of the Environment',
      'Lee Kong Chian School of Medicine',
      'Nanyang Business School (NBS)',
      'National Institute of Education',
      'Physical Education and Sports Science',
      'S. Rajaratnam School of International Studies',
      'School of Art, Design and Media',
      'School of Biological Sciences',
      'School of Chemical and Biomedical Engineering',
      'School of Civil and Environmental Engineering',
      'School of Computer Science and Engineering',
      'School of Electrical and Electronic Engineering',
      'School of Humanities',
      'School of Materials Science and Engineering',
      'School of Mechanical and Aerospace Engineering',
      'School of Physical and Mathematical Sciences',
      'School of Social Sciences',
      'Wee Kim Wee School of Communication and Information',
    ],
    showOthers: false,
  },
  course: {
    label: 'Course of Study',
    choices: [
      'Medicine',
      'Accountancy',
      'Business',
      'Accountancy and Business',
      'Arts (Education)',
      'Science (Education)',
      'Sport Science and Management',
      'Art, Design and Media',
      'Biological Sciences',
      'Biological Sciences and Psychology',
      'Biomedical Sciences and BioBusiness',
      'Biomedical Sciences and Chinese Medicine',
      'Bioengineering',
      'Chemical and Biomolecular Engineering',
      'Bioengineering & Economics',
      'Chemical & Biomolecular Engineering & Economics',
      'Civil Engineering',
      'Environmental Engineering',
      'Maritime Studies',
      'Civil Engineering & Economics',
      'Environmental Engineering & Economics',
      'Computer Engineering',
      'Computer Science',
      'Data Science and Artificial Intelligence',
      'Business and Computing',
      'Business and Computer Engineering',
      'Computer Engineering & Economics',
      'Computer Science & Economics',
      'Computer Science (part-time)',
      'Electrical and Electronic Engineering',
      'Information Engineering and Media',
      'Electrical & Electronic Engineering & Economics',
      'Information Engineering and Media & Economics',
      'Electrical and Electronic Engineering (Part-time)',
      'Chinese',
      'English',
      'History',
      'Linguistics and Multilingual Studies',
      'Philosophy',
      'English Literature and Art History',
      'Materials Engineering',
      'Materials Engineering & Economics',
      'Aerospace Engineering',
      'Mechanical Engineering',
      'Aerospace Engineering & Economics',
      'Mechanical Engineering & Economics',
      'Mechanical Engineering (Part-time)',
      'Chemistry and Biological Chemistry',
      'Mathematical Sciences',
      'Physics and Applied Physics',
      'Mathematical and Computer Sciences',
      'Mathematical Sciences and Economics',
      'Economics',
      'Psychology',
      'Public Policy and Global Affairs',
      'Sociology',
      'Economics and Media Analytics',
      'Economics and Psychology',
      'Economics and Public Policy and Global Affairs',
      'Psychology and Media Analytics',
      'Psychology and Linguistics and Multilingual Studies',
      'Environmental Earth Systems Science',
      'Environmental Earth Systems Science and Public',
      'Policy and Global Affairs',
      'Communication Studies',
    ],
    showOthers: true,
  },
  country: {
    label: 'Country',
    choices: [
      'Afghanistan',
      'Albania',
      'Algeria',
      'Andorra',
      'Angola',
      'Antigua and Barbuda',
      'Argentina',
      'Armenia',
      'Australia',
      'Austria',
      'Azerbaijan',
      'The Bahamas',
      'Bahrain',
      'Bangladesh',
      'Barbados',
      'Belarus',
      'Belgium',
      'Belize',
      'Benin',
      'Bhutan',
      'Bolivia',
      'Bosnia and Herzegovina',
      'Botswana',
      'Brazil',
      'Brunei',
      'Bulgaria',
      'Burkina Faso',
      'Burundi',
      'Cabo Verde',
      'Cambodia',
      'Cameroon',
      'Canada',
      'Central African Republic',
      'Chad',
      'Chile',
      'China',
      'Colombia',
      'Comoros',
      'Congo, Democratic Republic of the',
      'Congo, Republic of the',
      'Costa Rica',
      'Côte d’Ivoire',
      'Croatia',
      'Cuba',
      'Cyprus',
      'Czech Republic',
      'Denmark',
      'Djibouti',
      'Dominica',
      'Dominican Republic',
      'East Timor (Timor-Leste)',
      'Ecuador',
      'Egypt',
      'El Salvador',
      'Equatorial Guinea',
      'Eritrea',
      'Estonia',
      'Eswatini',
      'Ethiopia',
      'Fiji',
      'Finland',
      'France',
      'Gabon',
      'The Gambia',
      'Georgia',
      'Germany',
      'Ghana',
      'Greece',
      'Grenada',
      'Guatemala',
      'Guinea',
      'Guinea-Bissau',
      'Guyana',
      'Haiti',
      'Honduras',
      'Hungary',
      'Iceland',
      'India',
      'Indonesia',
      'Iran',
      'Iraq',
      'Ireland',
      'Israel',
      'Italy',
      'Jamaica',
      'Japan',
      'Jordan',
      'Kazakhstan',
      'Kenya',
      'Kiribati',
      'Korea, North',
      'Korea, South',
      'Kosovo',
      'Kuwait',
      'Kyrgyzstan',
      'Laos',
      'Latvia',
      'Lebanon',
      'Lesotho',
      'Liberia',
      'Libya',
      'Liechtenstein',
      'Lithuania',
      'Luxembourg',
      'Madagascar',
      'Malawi',
      'Malaysia',
      'Maldives',
      'Mali',
      'Malta',
      'Marshall Islands',
      'Mauritania',
      'Mauritius',
      'Mexico',
      'Micronesia, Federated States of',
      'Moldova',
      'Monaco',
      'Mongolia',
      'Montenegro',
      'Morocco',
      'Mozambique',
      'Myanmar (Burma)',
      'Namibia',
      'Nauru',
      'Nepal',
      'Netherlands',
      'New Zealand',
      'Nicaragua',
      'Niger',
      'Nigeria',
      'North Macedonia',
      'Norway',
      'Oman',
      'Pakistan',
      'Palau',
      'Panama',
      'Papua New Guinea',
      'Paraguay',
      'Peru',
      'Philippines',
      'Poland',
      'Portugal',
      'Qatar',
      'Romania',
      'Russia',
      'Rwanda',
      'Saint Kitts and Nevis',
      'Saint Lucia',
      'Saint Vincent and the Grenadines',
      'Samoa',
      'San Marino',
      'Sao Tome and Principe',
      'Saudi Arabia',
      'Senegal',
      'Serbia',
      'Seychelles',
      'Sierra Leone',
      'Singapore',
      'Slovakia',
      'Slovenia',
      'Solomon Islands',
      'Somalia',
      'South Africa',
      'Spain',
      'Sri Lanka',
      'Sudan',
      'Sudan, South',
      'Suriname',
      'Sweden',
      'Switzerland',
      'Syria',
      'Taiwan',
      'Tajikistan',
      'Tanzania',
      'Thailand',
      'Togo',
      'Tonga',
      'Trinidad and Tobago',
      'Tunisia',
      'Turkey',
      'Turkmenistan',
      'Tuvalu',
      'Uganda',
      'Ukraine',
      'United Arab Emirates',
      'United Kingdom',
      'United States',
      'Uruguay',
      'Uzbekistan',
      'Vanuatu',
      'Vatican City',
      'Venezuela',
      'Vietnam',
      'Yemen',
      'Zambia',
      'Zimbabwe',
    ],
    showOthers: true,
  },
};
